apply plugin: "com.android.application"

android {
    namespace "com.example.monapp"
    compileSdk 34

    defaultConfig {
        applicationId "com.example.monapp"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "0.1.0"

        externalNativeBuild {
            cmake {
                cppFlags "-std=c++17"
            }
        }

        ndk {
            abiFilters "arm64-v8a"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    externalNativeBuild {
        cmake {
            path "src/main/cpp/CMakeLists.txt"
        }
    }
}

dependencies {
}
